### ISSUE TITLE
Inconsistent number of entities with confidence=0

### ISSUE THREAD

**Issue by martingerlach** [MartinoMensio/spacy-dbpedia-spotlight#14] opened 2022-09-09 10:29 UTC
Hi, 
I think there might be an issue when setting the confidence-threshold to 0 following the documentation:
> nlp = spacy.blank("en")
> nlp.add_pipe('dbpedia_spotlight', config={'confidence': 0.})

The result seems to yield fewer entities than there should be. 

As an example, I looked at the following sentence from a randomly chosen Wikipedia article:
> Montgomery (Monty) Buell is the former chair of the Department of History and Philosophy at Walla Walla University in College Place, Washington, as well as current Professor of History.
 
Querying the dbpedia-spotlight API directly with confidence=0, yields 11 entities ([example-query](https://api.dbpedia-spotlight.org/en/annotate?text=Montgomery%20(Monty)%20Buell%20is%20the%20former%20chair%20of%20the%20Department%20of%20History%20and%20Philosophy%20at%20Walla%20Walla%20University%20in%20College%20Place,%20Washington,%20as%20well%20as%20current%20Professor%20of%20History.&confidence=0)).

When using the spacy-wrapper with `config={'confidence': 0.}` I get only 3 entities.
In contrast, I get 11 entities when using either `config={'confidence': 0.0001}` or  `config={'confidence': "0"}`

This seems to be a bug or maybe the documentation should be clear that the confidence should be specificied as a string?

**Comment by MartinoMensio** [comment] 2022-09-09 10:42
Hi @martingerlach,
Thank you very much for opening this issue! I reproduced it, and it's due to the checks I'm doing to see if the confidence parameter is set or not. I have not considered the edge case properly where the `0.` is indeed not "truthy". So it simply gets ignored. I will push a new version to fix that very soon!
As you already found out, using the string version is a workaround as it becomes "truthy".

Best,
Martino

**Comment by MartinoMensio** [comment] 2022-09-09 11:00
Hi again @martingerlach,
The issue has been resolved in version v0.2.3.
It now doesn't matter whether you specify the parameters as strings or floats as the spotlight API digests them in any form.
Please update with `pip install spacy-dbpedia-spotlight --upgrade` and let me know if you have further issues.

Martino

**Closed** 2022-09-29 10:36 UTC
Labels: bug
